config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get 'home/about'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'home#top'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "home/about"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_info.html.erb
<div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= render 'books/info', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.jpg"), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                   ♥<%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                   ♡<%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td>コメント数: <%= book.book_comments.count %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'books/info', user: @user, book: @book_new %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
　　　　　<tr>
           <td>
             <%= link_to user_path(@book.user) do %>
               <%= attachment_image_tag(@user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.jpg") %><br>
               <%= @user.name %>
             <% end %>
           </td>
           <td><%= link_to @book.title, book_path(@book.id) %></td>
           <td><%= @book.body %></td>
           <td>
             <% if @book.favorited_by?(current_user) %>
               <%= link_to book_favorites_path(@book), method: :delete do %>
                 ♥<%= @book.favorites.count %>
               <% end %>
             <% else %>
               <%= link_to book_favorites_path(@book), method: :post do %>
                 ♡<%= @book.favorites.count %>
               <% end %>
             <% end %>
           </td>
           <% if user_signed_in? && current_user == @book.user %>
             <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
             <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger" %></td>
           <% end %>
           <td>コメント数: <%= @book.book_comments.count %></td>
        　</tr>
        </tbody>
      </table>

      <table class="comments">
        <tbody>
          <% @book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= link_to user_path(book_comment.user) do %>
                  <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.jpg") %><br>
                  <%= book_comment.user.name %>
                <% end %>
              </td>
              <td>
                <%= book_comment.comment %>
              </td>
              <td>
                <% if current_user == book_comment.user %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>


      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <p><%= f.text_area :comment, class: "form-control", rows: "5" %></p>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>